- type: job
  id: LVCFalcon
  setPreference: true
  overrideConsoleVisibility: true
  canBeAntag: false
  name: job-name-los-vaq-falcon
  description: job-description-los-vaq-falcon
  playTimeTracker: LVCFalcon
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement
      department: LosVaquerosCartel
      min: 10800 # 3 hours
  startingGear: LVCFalcon
  alwaysUseSpawner: true
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-los-vaq
  access:
  - 
  - 
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - LosVaquerosCartel
      
- type: startingGear
  id: LVCFalconGear
  equipment:
- type: playTimeTracker
  id: LVCFalcon
