- type: job
  id: LVCUnderboss
  setPreference: true
  overrideConsoleVisibility: true
  canBeAntag: false
  name: job-name-los-vaq-underboss
  description: job-description-los-vaq-underboss
  playTimeTracker: LVCUnderboss
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement
      department: LosVaquerosCartel
      min: 32400 # 9 hours
  startingGear: LVCFalcon
  alwaysUseSpawner: true
  icon: "JobIconWarden"
  supervisors: job-supervisors-los-vaq
  access:
  - 
  - 
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - LosVaquerosCartel
      
- type: startingGear
  id: LVCUnderbossGear
  equipment:
- type: playTimeTracker
  id: LVCUnderboss
